cd FYC-Rewrite-V2
cd public
cd Configs
cd Replers
rm 3DS-Repo.json
rm EBook-Repo.json
rm Movie-Repo.json
rm PlayStation-Portable-Repo.json
rm TV-Repo.json
rm Windows-Apps-Repo.json
rm Music-Repo.json
wget https://raw.githubusercontent.com/Licnix/Repo/main/Config/Repos/Windows-Apps-Repo.json
wget https://raw.githubusercontent.com/Licnix/Repo/main/Config/Repos/TV-Repo.json
wget https://raw.githubusercontent.com/Licnix/Repo/main/Config/Repos/PlayStation-Portable-Repo.json
wget https://raw.githubusercontent.com/Licnix/Repo/main/Config/Repos/Movie-Repo.json
wget https://raw.githubusercontent.com/Licnix/Repo/main/Config/Repos/EBook-Repo.json
wget https://raw.githubusercontent.com/Licnix/Repo/main/Config/Repos/3DS-Repo.json
wget https://raw.githubusercontent.com/Licnix/Repo/main/Config/Repos/Music-Repo.json